name: Update Links Cache

on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours on the hour
  workflow_dispatch:         # allow manual run from Actions tab

permissions:
  contents: write

jobs:
  update-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Google Sheet (GViz JSON)
        run: |
          curl -sS "https://docs.google.com/spreadsheets/d/100MLUiSxyYpUfBhBM9hnqNd8EVXc4A4d2vZCkMVGoE4/gviz/tq?tqx=out:json" -o /tmp/sheet.json

      - name: Convert to links-cache.json
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const raw = fs.readFileSync('/tmp/sheet.json','utf8')
            // Strip GViz padding (everything before first "{", and trailing "];" etc.)
            .replace(/^[^{]*/,'')
            .replace(/;?\s*$/,'');
          const gviz = JSON.parse(raw);
          const rows = gviz.table?.rows ?? [];
          const data = rows.map(r => ({
            label: r.c?.[0]?.v || '',
            url:   r.c?.[1]?.v || ''
          })).filter(x => x.label && x.url);

          // Ensure target folder exists (repo layout has /links/)
          fs.mkdirSync('links', { recursive: true });
          fs.writeFileSync('links/links-cache.json', JSON.stringify(data, null, 2));
          console.log('Wrote links/links-cache.json with', data.length, 'items');
          NODE

      - name: Commit and push if changed
        run: |
          if git diff --quiet links/links-cache.json; then
            echo "No changes to commit."
          else
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add links/links-cache.json
            git commit -m "Update links cache from Google Sheets"
            git push
          fi
